version: "3.3"
services:
  #NGINX CONTAINER
  nginx:
    #define the container name
    container_name: nginx
    #Path to the Dockerfile
    build: ./sources/nginx/
    #Image specify the name of the image built when combined with build
    image: nginx
    #SSL ports mapping
    ports:
      - "443:443"
    #Nginx and wordpress use the same volume to stock website files
    volumes:
      - wordpress:/var/www/
    #Nginx is the only entrypoint, so the client communicate with nginx which communicate with others services
    networks:
      - back-network
    #Import environnement variable from .env
    env_file:
      - sources/.env
    #The container restart on failure
    restart: on-failure

  #MARIADB CONTAINER
  mariadb:
    container_name: mariadb
    build: ./sources/mariadb/
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - back-network
    env_file:
      - sources/.env
    restart: on-failure

  #WORDPRESS CONTAINER
  wordpress:
    container_name: wordpress
    build: ./sources/wordpress/
    image: wordpress
    volumes:
      - wordpress:/var/www/
    depends_on:
      - mariadb
    networks:
      - back-network
    env_file:
      - sources/.env
    restart: on-failure

volumes:
  #VOMUME THAT CONTAIN MARIADB DATABASE
  mariadb:
    driver_opts:
      type: none
      device: /home/user42/data/mariadb/
      o: bind

  #VOMUME THAT CONTAIN WORDPRESS DATABASE
  wordpress:
    driver_opts:
      type: none
      device: /home/user42/data/wordpress/
      o: bind

#DOCKER-NETWORK
networks:
  #NGINX NEED TO COMMUNICATE WITH THE OTHERS SERVICE SO HE SHARE A NETWORK WITH THEM
  back-network:
    driver: bridge