CREATE DATABASE IF NOT EXISTS MYSQL_DATABASE;
CREATE USER 'MYSQL_SUPER_USER'@'localhost';
SET PASSWORD FOR 'MYSQL_SUPER_USER'@'localhost' = PASSWORD('MYSQL_SUPER_PASSWORD');
GRANT ALL PRIVILEGES ON MYSQL_DATABASE.* TO 'MYSQL_SUPER_USER'@'localhost' IDENTIFIED BY 'MYSQL_SUPER_PASSWORD';
GRANT ALL ON MYSQL_DATABASE.* to 'MYSQL_SUPER_USER'@'%' IDENTIFIED BY 'MYSQL_SUPER_PASSWORD';

FLUSH PRIVILEGES;

CREATE USER 'MYSQL_LAMBDA_USER'@'localhost' IDENTIFIED BY 'MYSQL_LAMBDA_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'MYSQL_LAMBDA_USER'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE USER 'MYSQL_LAMBDA_USER'@'%' IDENTIFIED BY 'MYSQL_LAMBDA_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'MYSQL_LAMBDA_USER'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;