CREATE DATABASE IF NOT EXISTS MYSQL_DATABASE;
CREATE USER 'MYSQL_USER'@'localhost';
SET PASSWORD FOR 'wp_super'@'localhost' = PASSWORD('MYSQL_PASSWORD');
GRANT ALL PRIVILEGES ON wp_db.* TO 'MYSQL_USER'@'localhost' IDENTIFIED BY 'MYSQL_PASSWORD';
GRANT ALL ON MYSQL_DATABASE.* to 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';

FLUSH PRIVILEGES;

CREATE USER 'wp_user'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'wp_user'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE USER 'wp_user'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'wp_user'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;