-- Create database
CREATE DATABASE IF NOT EXISTS MYSQL_DATABASE;
-- Create database admin user and set admin priveleges
CREATE USER 'MYSQL_SUPER_USER'@'localhost';
SET PASSWORD FOR 'MYSQL_SUPER_USER'@'localhost' = PASSWORD('MYSQL_SUPER_PASSWORD');
GRANT ALL PRIVILEGES ON MYSQL_DATABASE.* TO 'MYSQL_SUPER_USER'@'localhost' IDENTIFIED BY 'MYSQL_SUPER_PASSWORD';
GRANT ALL ON MYSQL_DATABASE.* to 'MYSQL_SUPER_USER'@'%' IDENTIFIED BY 'MYSQL_SUPER_PASSWORD';
FLUSH PRIVILEGES;
-- Create database lambda user and set read privileges
CREATE USER 'MYSQL_LAMBDA_USER'@'localhost' IDENTIFIED BY 'MYSQL_LAMBDA_PASSWORD';
GRANT SELECT ON *.* TO 'MYSQL_LAMBDA_USER'@'localhost';
FLUSH PRIVILEGES;
